export const UPDATE_INPUT_TEXT_VALUE = 'UPDATE_INPUT_VALUE';
export const UPDATE_INPUT_FILE = 'UPDATE_INPUT_FILE';
export const NOVALIDATE_INPUT_VALUE = 'NOVALIDATE_INPUT_VALUE';
export const NEXT_FORM = 'NEXT_FORM';
export const PREV_FORM = 'PREV_FORM';
export const DEACTIVE_FORM = 'DEACTIVE_FORM';
export const GET_WAIT_FORM = 'GET_WAIT_FORM';
export const SUCCES_FORM = 'SUCCES_FORM';